# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-uA9LQHX0KcfcMihfcKMag4TK2hqQNm
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/customer_experience_data.csv')
print(df.head())

sayisal_sutunlar = df.select_dtypes(include='number').columns
kategorik_sutunlar = df.select_dtypes(include='object').columns

print("Sayısal sütunlar:", list(sayisal_sutunlar))
print("Kategorik sütunlar:", list(kategorik_sutunlar))

print("\nSayısal sütunlar için özet istatistikler:")
print(df[sayisal_sutunlar].describe())

print("\nKategorik sütunlar için frekans tablosu:")
for col in list(kategorik_sutunlar)[:3]:
    print(f"\n{col} sütunu değer dağılımı:")
    print(df[col].value_counts())

for col in kategorik_sutunlar:
    print(f"\n{col} sütunu değer dağılımı:")
    print(df[col].value_counts())

#Cinsiyet dağılımı
sns.countplot(x='Gender', data=df)
plt.title('Cinsiyet Dağılımı')
plt.show()

#Lokasyon dağılımı
sns.countplot(x='Location', data=df)
plt.title('Lokasyon Dağılımı')
plt.show()

#Retention durumunun dağılımı (pasta grafiği)
df['Retention_Status'].value_counts().plot.pie(autopct='%1.1f%%', colors=['#66b3ff','#ff9999'])
plt.title('Retention Durumu')
plt.ylabel('')
plt.show()


#Müşteri tutulumu (Retention Status) dağılımı
df['Retention_Status'].value_counts().plot.pie(autopct='%1.1f%%', colors=['#66b3ff','#ff9999'])
plt.title('Müşteri Tutulumu')
plt.ylabel('')
plt.show()